# Generated by Django 3.2.17 on 2023-02-02 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_studentinfos'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInfos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('schoolName', models.CharField(max_length=20, verbose_name='学校名称')),
                ('schoolType', models.CharField(choices=[('学前', '学前'), ('小学', '小学'), ('初中', '初中'), ('高中', '高中'), ('大学', '大学'), ('培训机构', '培训机构')], max_length=8, verbose_name='学校类别')),
                ('abCode', models.CharField(max_length=6, verbose_name='高德区域编码')),
                ('schoolCode', models.CharField(max_length=10, verbose_name='高德学校ID')),
            ],
            options={
                'verbose_name': '学校信息',
                'verbose_name_plural': '学校信息',
            },
        ),
        migrations.CreateModel(
            name='GradeInfos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gradeName', models.CharField(max_length=20, verbose_name='年级名称')),
                ('schoolInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_id', to='Users.schoolinfos')),
            ],
            options={
                'verbose_name': '年级信息',
                'verbose_name_plural': '年级信息',
            },
        ),
        migrations.CreateModel(
            name='ClassInfos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('className', models.CharField(max_length=20, verbose_name='班级名称')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_id', to='Users.gradeinfos')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_id', to='Users.userinfos')),
            ],
            options={
                'verbose_name': '班级信息',
                'verbose_name_plural': '班级信息',
            },
        ),
    ]
