# Generated by Django 3.2.17 on 2023-02-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20230202_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinfos',
            name='abCode',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='高德区域编码'),
        ),
        migrations.AlterField(
            model_name='schoolinfos',
            name='schoolCode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='高德学校ID'),
        ),
    ]
