# Generated by Django 3.2.17 on 2023-02-02 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0006_auto_20230202_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfos',
            name='authUser',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
