# Generated by Django 3.2.17 on 2023-02-02 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabelInfos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('labelName', models.CharField(max_length=50, verbose_name='标签名称')),
                ('fatherLabel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father_id', to='Records.labelinfos')),
            ],
            options={
                'verbose_name': '标签列表',
                'verbose_name_plural': '标签列表',
            },
        ),
        migrations.CreateModel(
            name='RecordInfos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='内容')),
                ('isShared', models.BooleanField(default=False, verbose_name='是否分享')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('label', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='label_id', to='Records.labelinfos')),
            ],
            options={
                'verbose_name': '记录表',
                'verbose_name_plural': '记录表',
            },
        ),
    ]
