# Generated by Django 3.2.17 on 2023-02-02 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordinfos',
            name='label',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label_id', to='Records.labelinfos'),
        ),
    ]
