# Generated by Django 3.2.17 on 2023-02-02 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20230202_2138'),
        ('Records', '0003_recordinfos_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordinfos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userInfo_id', to='Users.userinfos'),
        ),
    ]
