# Generated by Django 3.2.17 on 2023-02-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20230202_2138'),
        ('Records', '0004_alter_recordinfos_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordinfos',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='studentInfo_id', to='Users.StudentInfos'),
        ),
    ]
