# Generated by Django 3.2.17 on 2023-02-02 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0007_alter_labelinfos_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgInfos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imgUrl', models.ImageField(upload_to='RecordImg', verbose_name='图片地址')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordImg_id', to='Records.recordinfos')),
            ],
            options={
                'verbose_name': '图片地址',
                'verbose_name_plural': '图片地址',
            },
        ),
    ]
